apiVersion: v1
kind: Service
metadata:
  name: {{ include "gradyent-task.fullname" . }}
  labels:
    app: {{ include "gradyent-task.name" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "gradyent-task.name" . }}
