replicaCount: 2
image:
  repository: gradyent/tech-interview
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
resources: {}
readinessProbe:
  path: /
  port: 8080
livenessProbe:
  path: /hello
  port: 8080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: grayent.example.com
      paths:
        - path: /
          pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
