configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: gradyent-velero-backups
      config:
        region: eu-west-1
        s3ForcePathStyle: true
serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: "${VELERO_IAM_ROLE_ARN}"
