datadog:
  site: "datadoghq.com"
  apiKeyExistingSecret: "datadog-secret"
  otelCollector:
    enabled: true
    ports:
      - containerPort: 4317
        hostPort: 4317
        name: "otel-grpc"
      - containerPort: 4318
        hostPort: 4318
        name: "otel-http"
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"
  logs:
    enabled: true
    containerCollectAll: true
  asm:
    threats:
      enabled: true
  securityAgent:
    runtime:
      enabled: true
    compliance:
      enabled: true
  sbom:
    containerImage:
      enabled: true
    host:
      enabled: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
  processAgent:
    processCollection: true
